### ISSUE TITLE
공공 데이터 리스트 수집

### ISSUE THREAD

**Issue by BBARRY-Lee** [Paul-scpark/AI-dev-course-prj#9]
- BS4, Selenium 활용
- [공공데이터 포털](https://www.data.go.kr/), [AI Hub](https://www.aihub.or.kr/), [서울 열린데이터 광장](https://data.seoul.go.kr/), [데이터 통합 지도](https://www.bigdata-map.kr/), [국가 통계 포털](https://kosis.kr/index/index.do), [지역 데이터 개방](https://www.localdata.go.kr/)
- 브랜치 생성 방법: 이슈 번호 - 이니셜 (`feature/#9-PSC`)
---
- 성찬
  - [x] 공공데이터 포털
  - [x] AI Hub
  - [x] 데이터 통합 지도
- 상암
  - [x] 서울 열린데이터 광장
- 지윤
  - [x] 지역 데이터 개방

**Comment by augustinLib** [comment]
브랜치 이름을 #로 시작하는 경우 브랜치 생성이 불가능한것같습니다. 임시로 #을 제외한 9-LSA 로 브랜치 생성하였습니다

**Comment by Paul-scpark** [comment]
> 브랜치 이름을 #로 시작하는 경우 브랜치 생성이 불가능한것같습니다. 임시로 #을 제외한 9-LSA 로 브랜치 생성하였습니다

@augustinLib 상암님, 혹시 브랜치 이름을 `feature/#9 - LSA`로 수정 가능할까요? feature 브랜치라는 것을 언급하면서 issue 번호를 쓰면 좋을 것 같아서요..! 미리 이야기 한다는걸 깜빡했었네요...!!

**Comment by augustinLib** [comment]
> 

네 아직 푸쉬하지는 않았으니깐 바로 브랜치명 변경하고 추후에 푸쉬할때는 바뀐 브랜치명으로 푸쉬하겠습니다!

**Comment by Paul-scpark** [comment]
## 데이터 수집 가이드라인

[공공데이터에서 제공하는 데이터 정리 스프레드 시트](https://docs.google.com/spreadsheets/d/1JamX9wXn67BPBxN_C4H-JblBFz-0nkMzQffRNjGj_aQ/edit?usp=sharing)

### 데이터 수집의 목적
- 우리가 생각하는 `데이터 아카이빙` 서비스의 필요성을 설득할 수 있는 기초 자료 획득 (프로토타입 제작에 매우 큰 도움이 될 것 같음)
- 우리가 같이 논의했던 여러 가설들에 대한 실제 데이터들의 현황, 상황 파악
  - 실제 데이터를 다운받으며 사용하는 유저의 관점에서 공감하면서 불편하다면 어떤게 불편했고, 좋았다면 어떤게 좋았는지 고민
  - 우리가 생각하는 최종적인 프로토타입에 추가되었으면 좋겠다고 생각하는 Edge에 대한 고민

### 작업하면서 정리해두면 좋을 것 같은 특이사항
- 데이터의 규격 (column 값)이 데이터마다 통일되어 비슷하게 제공되고 있는지?
- 데이터에 대한 설명이 충분히 길게 표현되어 있는지?, 데이터의 유형 (Label)은 있는지?
- 데이터 사용 권한이 어떻게 되어 있는지? (유료 또는 무료로 사용 가능?, API KEY 발급 필요? 등)
- 유저들이 사용 가능 (다운 가능)한 데이터의 포맷이 존재한지? (CSV, XML, API 등)
- 예시
  - `공공데이터포털`의 경우에는 제공하는 데이터 규격이 데이터마다 다른게 많음
  - `AI Hub`의 경우에는 데이터 규격이 전반적으로 잘 통일되어 있음
  - `서울 열린데이터 광장`의 경우에는 해당 데이터에 대한 설명이 한줄로 간단함. 전반적인 규격은 잘 통일되어 있음
  - `국가 통계 포털`의 경우에는 데이터에 대한 소개는 아예 없고, 통계청에서 제공하다보니 엑셀 형태의 데이터만 제공되고 있음
  - `지역 데이터 개방`의 경우에는 데이터에 대한 소개는 아예 없고, 파일 형태보다는 홈페이지 내에서 text 형태의 데이터만 제공

### 최종적으로 수집한 데이터 형태
- 아래 그림과 같이 페이지에서 제공하는 데이터 수집 (가능한 페이지에서 제공하고 있는 모든 데이터 - 무리는 안해도 괜찮아요!)
- 최소한 꼭 필요하다고 생각되는 데이터
  - 데이터 이름, 데이터 분류 체계 (Label), 데이터 설명, 데이터 형태 (CSV, XML, API 등)



![Image](https://user-images.githubusercontent.com/75621410/195392123-06ea9854-5f36-4cba-a0e2-7c6dce94bff4.png)

**Comment by BBARRY-Lee** [comment]
브랜치 명 네이밍 시 공백 허용이 안 되는 것 같아서, 다음과 같이 공백 제외하고 네이밍하겠습니다.
`feature/#9-LJY`

**Comment by Paul-scpark** [comment]
> 브랜치 명 네이밍 시 공백 허용이 안 되는 것 같아서, 다음과 같이 공백 제외하고 네이밍하겠습니다. `feature/#9-LJY`

앗..! 맞네요~~ 저도 수정하겠습니다!
